### ISSUE TITLE
方案2和方案一存在同样的问题，应该在success中也处理一下

### ISSUE THREAD

**Issue by Zalezale** [wsafight/personBlog#35]

**Comment by wsafight** [comment]
非常感谢您的 issue，不过我希望

-  可以提供足够的上下文以便我来参考那篇文章的问题，或者在具体文章下指出问题。
-  我分析是 [前端 api 请求缓存方案 ](https://github.com/wsafight/personBlog/issues/2) 下的问题，不过我是渐进提出方案的。并不是完全代码的解读，在方案 1 的基础上可以轻松分析出方案 2 的代码，并非不处理
